package proyecto.interfaces;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.openide.util.Exceptions;
import proyecto.classes.LogicaMenu;
import proyecto.classes.Plat;
import proyecto.classes.tipo;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author admin
 */
public class JFraMenuPrincipal extends javax.swing.JFrame {

    public final ArrayList<Plat> menu;
    String nomRestaurant;
    String idiomaRestaurant;
    SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy, HH:mm");
    Date horaCierreRestaurant=Date.from(Instant.now());
    int validacionLicencia = 0;
    int validacionCamarero = 0;
    int validacionMenu = 0;

    String txtFile = System.getProperty("user.dir") + "/src/Archivos necesarios/llicenciesValides.csv";

    /**
     * Creates new form JFraMenuPrincipal
     *
     */
    public JFraMenuPrincipal() {
        this.menu = LogicaMenu.getMenu();
        nomRestaurant = "Restaurante";
        idiomaRestaurant = "Castellano";
        initComponents();
    }
    
    public void setValidacionCamarero(int validacion){
        validacionCamarero = validacion;
        jLabelCamarero.setVisible(false);
    }

    public String getNomRestaurant() {
        return nomRestaurant;
    }

    public String getIdiomaRestaurant() {
        return idiomaRestaurant;
    }

    public Date getHoraCierreRestaurant() {
        return horaCierreRestaurant;
    }

    public void setConfigRestaurante(String nom, String idioma, Date horaCierre) throws ParseException {
        nomRestaurant = nom;
        idiomaRestaurant = idioma;
        horaCierreRestaurant = new Date(horaCierre.getTime());
    }
    
    public void validaciones(){
        if (validacionLicencia > 0 && validacionMenu > 0 && validacionCamarero > 0){
            jBuCargarRestaurante.setEnabled(true);
            jLabelInsertar.setVisible(false);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jBuCargarRestaurante = new javax.swing.JButton();
        jLabelInsertar = new javax.swing.JLabel();
        jLabelLicencia = new javax.swing.JLabel();
        jLabelCamarero = new javax.swing.JLabel();
        jLabelMenu = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMeCargar = new javax.swing.JMenu();
        jMenuCargarLicencia = new javax.swing.JMenuItem();
        jMeDatosCamarero = new javax.swing.JMenuItem();
        jMeMenuDia = new javax.swing.JMenuItem();
        jMeConfigGeneral = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBuCargarRestaurante.setText("Cargar restaurante");
        jBuCargarRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuCargarRestauranteActionPerformed(evt);
            }
        });

        jLabelInsertar.setText("Por favor, inserta:");

        jLabelLicencia.setText("- Licencia valida");

        jLabelCamarero.setText("- Datos del camarero");

        jLabelMenu.setText("- Menu del dia");

        jMeCargar.setText("Cargar");
        jMeCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMeCargarActionPerformed(evt);
            }
        });

        jMenuCargarLicencia.setText("Cargar archivos licencia");
        jMenuCargarLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCargarLicenciaActionPerformed(evt);
            }
        });
        jMeCargar.add(jMenuCargarLicencia);

        jMeDatosCamarero.setText("Cargar / añadir datos del camarero");
        jMeDatosCamarero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMeDatosCamareroActionPerformed(evt);
            }
        });
        jMeCargar.add(jMeDatosCamarero);

        jMeMenuDia.setText("Cargar menu del dia");
        jMeMenuDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMeMenuDiaActionPerformed(evt);
            }
        });
        jMeCargar.add(jMeMenuDia);

        jMeConfigGeneral.setText("Config. general del programa ");
        jMeConfigGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMeConfigGeneralActionPerformed(evt);
            }
        });
        jMeCargar.add(jMeConfigGeneral);

        jMenuBar1.add(jMeCargar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBuCargarRestaurante)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelLicencia)
                        .addComponent(jLabelInsertar)
                        .addComponent(jLabelCamarero)
                        .addComponent(jLabelMenu)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInsertar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLicencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCamarero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBuCargarRestaurante)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCargarLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCargarLicenciaActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser(System.getProperty("user.dir"));
        int returnVal = chooser.showOpenDialog(null);
        File file = null;
        String[] partes = null;

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            System.out.println("You chose to open this file: "
                    + chooser.getSelectedFile().getName());
            file = chooser.getSelectedFile();
        }
        if (file != null) {
            try (BufferedReader bufr = new BufferedReader(new InputStreamReader(new FileInputStream(file)))) {
                String linia = bufr.readLine();
                partes = linia.split(",");
                bufr.close();
            } catch (IOException ex) {
                Logger.getLogger(JFraMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }

            try (BufferedReader bufr2 = new BufferedReader(new FileReader(txtFile))) {
                String linia;
                boolean resultado = false;
                SimpleDateFormat date = new SimpleDateFormat("HH:mm:ss yyyy-MM-dd");
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH:mm:ss yyyy-MM-dd");
                Date datenow = date.parse(dtf.format(LocalDateTime.now()));

                while ((linia = bufr2.readLine()) != null && !resultado) {
                    Date fechaCSV = date.parse(partes[1]);
                    if (partes[0].equals(linia) && datenow.before(fechaCSV)) {
                        resultado = true;
                    }
                }
                bufr2.close();
                if (resultado) {
                    JOptionPane.showMessageDialog(this, "Licencia validada", "Validacion licencia", JOptionPane.INFORMATION_MESSAGE);
                    validacionLicencia = 1;
                    validaciones();
                    jLabelLicencia.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Licencia invalida", "Validacion licencia", JOptionPane.ERROR_MESSAGE);
                }
            } catch (IOException | ParseException ex) {
                Logger.getLogger(JFraMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jMenuCargarLicenciaActionPerformed

    private void jMeDatosCamareroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMeDatosCamareroActionPerformed
        // TODO add your handling code here:
        JDiaCamarero visible = new JDiaCamarero(this, false, this);
        visible.setVisible(true);
    }//GEN-LAST:event_jMeDatosCamareroActionPerformed

    private void jMeCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMeCargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMeCargarActionPerformed

    private void jMeMenuDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMeMenuDiaActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser(System.getProperty("user.dir"));
        int returnVal = chooser.showOpenDialog(null);
        File file = null;
        String[] partes;
        String linea;

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            System.out.println("You chose to open this file: "
                    + chooser.getSelectedFile().getName());
            file = chooser.getSelectedFile();
        }
        try (BufferedReader br = new BufferedReader(new InputStreamReader(new FileInputStream(file)))) {
            Plat p;
            while ((linea = br.readLine()) != null) {
                partes = linea.split(",", 6);
                //if (partes[4]){System.out.println("si");}
                if (partes[2].contains("primer")) {
                    p = new Plat(partes[0], Double.valueOf(partes[1]), tipo.primer);
                    if (partes[3].contains("lactics")) {
                        p.setLàctics(true);
                    } else if (partes[3].contains("carn")) {
                        p.setCarn(true);
                    } else if (partes[3].contains("ou")) {
                        p.setOu(true);
                    } else if (partes[3].contains("peix")) {
                        p.setPeix(true);
                    } else if (partes[3].contains("gluten")) {
                        p.setGluten(true);
                    }

                    if (partes[4].contains("lactics")) {
                        p.setLàctics(true);
                    } else if (partes[4].contains("carn")) {
                        p.setCarn(true);
                    } else if (partes[4].contains("ou")) {
                        p.setOu(true);
                    } else if (partes[4].contains("peix")) {
                        p.setPeix(true);
                    } else if (partes[4].contains("gluten")) {
                        p.setGluten(true);
                    }

                    if (partes[5].contains("lactics")) {
                        p.setLàctics(true);
                    } else if (partes[5].contains("carn")) {
                        p.setCarn(true);
                    } else if (partes[5].contains("ou")) {
                        p.setOu(true);
                    } else if (partes[5].contains("peix")) {
                        p.setPeix(true);
                    } else if (partes[5].contains("gluten")) {
                        p.setGluten(true);
                    }

                    menu.add(p);
                    validacionMenu = 1;
                    validaciones();
                    jLabelMenu.setVisible(false);
                } else if (partes[2].contains("segon")) {
                    p = new Plat(partes[0], Double.valueOf(partes[1]), tipo.segon);
                    if (partes[3].contains("lactics")) {
                        p.setLàctics(true);
                    } else if (partes[3].contains("carn")) {
                        p.setCarn(true);
                    } else if (partes[3].contains("ou")) {
                        p.setOu(true);
                    } else if (partes[3].contains("peix")) {
                        p.setPeix(true);
                    } else if (partes[3].contains("gluten")) {
                        p.setGluten(true);
                    }

                    if (partes[4].contains("lactics")) {
                        p.setLàctics(true);
                    } else if (partes[4].contains("carn")) {
                        p.setCarn(true);
                    } else if (partes[4].contains("ou")) {
                        p.setOu(true);
                    } else if (partes[4].contains("peix")) {
                        p.setPeix(true);
                    } else if (partes[4].contains("gluten")) {
                        p.setGluten(true);
                    }

                    if (partes[5].contains("lactics")) {
                        p.setLàctics(true);
                    } else if (partes[5].contains("carn")) {
                        p.setCarn(true);
                    } else if (partes[5].contains("ou")) {
                        p.setOu(true);
                    } else if (partes[5].contains("peix")) {
                        p.setPeix(true);
                    } else if (partes[5].contains("gluten")) {
                        p.setGluten(true);
                    }

                    menu.add(p);
                    validacionMenu = 1;
                    validaciones();
                    jLabelMenu.setVisible(false);

                } else if (partes[2].contains("postre")) {
                    p = new Plat(partes[0], Double.valueOf(partes[1]), tipo.postre);
                    if (partes[3].contains("lactics")) {
                        p.setLàctics(true);
                    } else if (partes[3].contains("carn")) {
                        p.setCarn(true);
                    } else if (partes[3].contains("ou")) {
                        p.setOu(true);
                    } else if (partes[3].contains("peix")) {
                        p.setPeix(true);
                    } else if (partes[3].contains("gluten")) {
                        p.setGluten(true);
                    }

                    if (partes[4].contains("lactics")) {
                        p.setLàctics(true);
                    } else if (partes[4].contains("carn")) {
                        p.setCarn(true);
                    } else if (partes[4].contains("ou")) {
                        p.setOu(true);
                    } else if (partes[4].contains("peix")) {
                        p.setPeix(true);
                    } else if (partes[4].contains("gluten")) {
                        p.setGluten(true);
                    }

                    if (partes[5].contains("lactics")) {
                        p.setLàctics(true);
                    } else if (partes[5].contains("carn")) {
                        p.setCarn(true);
                    } else if (partes[5].contains("ou")) {
                        p.setOu(true);
                    } else if (partes[5].contains("peix")) {
                        p.setPeix(true);
                    } else if (partes[5].contains("gluten")) {
                        p.setGluten(true);
                    }

                    menu.add(p);
                    validacionMenu = 1;
                    validaciones();
                    jLabelMenu.setVisible(false);
                }

            }
            br.close();
        } catch (IOException ex) {
            Logger.getLogger(JFraMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMeMenuDiaActionPerformed

    private void jMeConfigGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMeConfigGeneralActionPerformed
        // TODO add your handling code here:
        JDiaConfigGeneral visible = new JDiaConfigGeneral(this, false);
        visible.setVisible(true);
    }//GEN-LAST:event_jMeConfigGeneralActionPerformed

    private void jBuCargarRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuCargarRestauranteActionPerformed
        Sala sala = new Sala(this, false);
        this.setVisible(false);
        sala.setVisible(true);
    }//GEN-LAST:event_jBuCargarRestauranteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFraMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFraMenuPrincipal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBuCargarRestaurante;
    private javax.swing.JLabel jLabelCamarero;
    private javax.swing.JLabel jLabelInsertar;
    private javax.swing.JLabel jLabelLicencia;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JMenu jMeCargar;
    private javax.swing.JMenuItem jMeConfigGeneral;
    private javax.swing.JMenuItem jMeDatosCamarero;
    private javax.swing.JMenuItem jMeMenuDia;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCargarLicencia;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
